export enum Dimension {
    FORMALIZATION = "FORMALIZATION",
    ACCOUNTING = "ACCOUNTING",
    FUNDING = "FUNDING",
}

export enum MaturityLevel {
    NEEDS_STRENGTHENING = "NEEDS_STRENGTHENING",
    IN_PROGRESS = "IN_PROGRESS",
    ADVANCED = "ADVANCED",
}